[package]
name = "lox"
version = "0.1.0"
authors = ["davidnuon"]

[dependencies]
clap = "*"
chrono = "*"
regex = "0.2"
libc = "*"

[target.x86_64-unknown-linux-gnu.dependencies]
[target.i686-unknown-linux-gnu.dependencies]
pentry = "*"